### ISSUE TITLE
Getting xray-rails to work with Sublime Text 3

### ISSUE THREAD

**Issue by johnkferguson** [brentd/xray-rails#34]
I've been having trouble getting `xray-rails` to open files using Sublime Text 3.

I have my ``~/.xrayconfig` file defined as follows:

```

---
:editor: '/Applications/Sublime Text.app/Contents/SharedSupport/bin/subl'
```

I'm not sure why it won't open files as I can open files with Sublime from the command line by running the following command:
`'/Applications/Sublime Text.app/Contents/SharedSupport/bin/subl' name_of_file`

I'm pretty baffled on why it won't work with `xray-rails`. The only other piece of relevant information that I can think of is that I have `oh-my-zsh` installed on my machine.

Any ideas on how to get this to work or what I could be doing wrong?

Thanks a lot.

**Comment by juhguu** [comment]
I have the same problem. Any idea?

**Comment by labocho** [comment]
Do you use tmux with OSX?
I had same problem.

```
$ tmux new-window irb
require "open3"
Open3.capture3('/usr/local/bin/subl /etc/profile')
# Activate SublimeText. But does not open file
```

And fixed by using [reattach-to-user-namespace](https://github.com/ChrisJohnsen/tmux-MacOSX-pasteboard)
```
$ tmux new-window 'reattach-to-user-namespace irb'
require "open3"
Open3.capture3('/usr/local/bin/subl /etc/profile')
# Open file
```

**Comment by brentd** [comment]
Ah, I see. I personally do not use tmux, precisely because of the env issues like this it causes :)

Is there anything we can add to xray to workaround this?

**Comment by deepakmahakale** [comment]
If you use sublime simply create `symlink` for `subl` to `usr/local/bin/`. As that is where xray search for subl https://github.com/brentd/xray-rails#configuration

```bash
 sudo ln -s /usr/bin/subl /usr/local/bin/subl
```
Or, You can just create a `~/.xrayconfig` in root and add the following

```yaml
:editor: '/usr/local/bin/subl'
```
