### ISSUE TITLE
causes encoding conflict with letter_opener

### ISSUE THREAD

**Issue by pilgunboris** [brentd/xray-rails#45]
Hello.

when I'm using both:
 - xray-rails  
and
 - https://github.com/ryanb/letter_opener

letter_opener opens emails with body in wrong encoding: 

![image](https://cloud.githubusercontent.com/assets/897631/3707241/f6ba824a-1432-11e4-8cd7-65ddee179f72.png)

without xray-rails it works correctly.

 - ruby '2.1.2'
 - 'rails', '3.2.18'

**Comment by brentd** [comment]
This is hopefully fixed in v0.1.17, as Xray should no longer be trying to augment mailer templates.
