### ISSUE TITLE
Skip xray for email templates

### ISSUE THREAD

**Issue by barthez** [brentd/xray-rails#48]
XRay adds its comments into mailers templates (html/text whatever). It get little messy when I try tests my emails generated in development environment against SPAM test and other, because it's complaining about this comments. It it also impossible to inspect emails by XRay, so why these comments should even be there?

**Comment by tinynumbers** [comment]
Any updates on this issue?

**Comment by brentd** [comment]
v0.1.17 should no longer augment mailer templates
