### ISSUE TITLE
commands don't work!

### ISSUE THREAD

**Issue by FranMoya** [brentd/xray-rails#52]
First of all, great job!
I've installed the gem and did the bundle for my Rails app. I check that xray-rails gem is working but when I apply cmd+shift+x it doesn't work.
I've modified the commands (cmd+shift+x) to (cmd+shift+c) and it works (xray-rails paints my partials) so I notice that when I press cmd+shift, when I try to press x it doesn't work.
Can I suggest to apply changes in order to custom de commands?
Could anyone tell me what is not working it well?

Thank you!

**Comment by brentd** [comment]
Hey @FranMoya,

`cmd+shift+c` is actually the shortcut for Chrome's dev tools. Is that what you're seeing?

When you go to a page in your app, do you see the text "Ready to Xray. Press cmd+shift+x to scan your UI." in the console?

**Comment by FranMoya** [comment]
Hi brendt, "Ready to Xray" appears in my chrome console but cmd+shift+x command doesn't work, so I can't scan my UI. I changed de JS file in order to modify key = 80 to key = 67 (that it is "c" key) and it works but of course, the gem only works if I press "x" key and that is my problem, I can't make that cmd+shift+x works in mi mac :S (it´s weird, I know but it is a real problem)
Thanks!

**Comment by Gee-Bee** [comment]
I can confirm this. I'm working on Fedora Linux 21 with Gnome 3.14 de. 
Changing keycode in `xray.js.coffee` to something else (for example 69 for `e`) is a workaround for me.
Is there any proper solution?

**Comment by FranMoya** [comment]
Finally I modified the coffee.js file in order to permit to keydown two different keys(x=88 & v=86), it works great!
Thanks @brentd and @Gee-Bee !

**Comment by passalini** [comment]
+1 
Chrome 43.0.2357.81 (64-bit) - Mint 17.
Works fine in firefox.

@FranMoya can you show me your xray.js.coffee?

**Comment by passalini** [comment]
Coming back just to say... My problem was because an extension was using the same command.. So...
-1

**Comment by MiguelSavignano** [comment]
Hi, I have the same problem.

My solution it's open the javascript console and type
```javascript
Xray.show()
```
