### ISSUE TITLE
Xray-rails and Spree 3-0-stable

### ISSUE THREAD

**Issue by misteral** [brentd/xray-rails#55]
Hi. 

Xray-rails do not work at spree 3-0-stable.
cmd+shift+x not work, Chrome console do not have Xray ready message.

Chrome console screenshot http://take.ms/FOHHH

please help.

**Comment by mattbrictson** [comment]
It's because xray-rails doesn't work with sprockets 3. I just verified this.

As a workaround, add this to your Gemfile:

```ruby
gem 'sprockets', '< 3.0'
```

And then run:

```
bundle update sprockets
```

**Comment by brentd** [comment]
Should be fixed now thanks to @mattbrictson. Please retest w/ version 0.1.16 and close if fixed!

**Comment by misteral** [comment]
Yes, all good now. Thanks to @mattbrictson!
