### ISSUE TITLE
"require: false" option

### ISSUE THREAD

**Issue by jbodah** [brentd/xray-rails#57]
It would be nice to have documentation on how to use `xray-rails` with the `require: false` option in the Gemfile. On initial pass I tried using an environment variable to specify whether or not to require `xray-rails` at the top of my `development.rb`, but that didn't seem to do it. Works perfectly in Rails 4.1 and FF by requiring it in the Gemfile.

It look like xray works by using a Rails engine. I'm not too keen on how engines work. I'm assuming there's some dynamic lookup for ancestors on app load?

**Comment by brentd** [comment]
We actually require xray-rails manually in the spec suite's dummy Rails app, and it works fine.

https://github.com/brentd/xray-rails/blob/master/spec/dummy/config/application.rb#L12

I tried moving it to development.rb as well and it seemed to work. Nothing too crazy going on with the middleware - requiring the gem anywhere should work!

**Comment by jbodah** [comment]
Cool thanks!

**Comment by tombroomfield** [comment]
Hi Guys,
I am attempting to do the same as @jbodah - Conditionally requiring the gem at the top of the development.rb file. No errors, but xray simply does not show. Works perfectly if I don't add the `require: false` to the gem file.

Any ideas?
