### ISSUE TITLE
Not require config.assets.debug?

### ISSUE THREAD

**Issue by cannikin** [brentd/xray-rails#6]
Loving this gem! Is there anything we can do to make `config.assets.debug = true` _not_ be required? We have quite a few CSS/JS files in our app and setting that to `false` shaves a second or two off our render time in development. Is this so that JS views can be rendered properly? For our project it would be worth the tradeoff.

Would it be possible to configure the engine so we can just manually add a line to application.js to include the xray assets?  `//= require xray` or something similar? Maybe just add the caveat that if you configure your app this way you won't be able to xray JS views?

**UPDATE** I actually just tried this and it works! So maybe this is just a request to update the documentation to mention this as an option. :)

Thanks!
Rob

**Comment by NazarK** [comment]
When config.assets.debug=false and 'xray' gem is only for development environment.
Requiring  in application.js and in application.scss breaks production.
Conditional include in layout file instead worked for me (haml code).

```
- if Rails.env.development?
     = stylesheet_link_tag "xray", media: 'all', 'data-turbolinks-track' => 'reload'
     = javascript_include_tag "xray", 'data-turbolinks-track' => 'reload'
```
