### ISSUE TITLE
Support for Sprockets 4

### ISSUE THREAD

**Issue by patleb** [brentd/xray-rails#74]
It's currently not working with Sprockets 4: https://github.com/rails/sprockets/blob/master/guides/extending_sprockets.md

**Comment by patleb** [comment]
I've made it worked in my fork, but I've also some personal modifications, so it might be a good starting point for a pull request if you want to take a look : https://github.com/patleb/xray-rails/commit/a5bc3f03a1514d145a848fedcd27cefbe9876950

**Comment by mattbrictson** [comment]
Hi, thanks for the report and the commit. Can you provide some more background to bring us up to speed?

* What changed in Sprockets 4 that breaks xray-rails?
* What error message or undesirable behavior does this cause?
* How does your commit fix it?
* Are these fixes backwards-compatible with Sprockets 2 and 3?

**Comment by baburdick** [comment]
@mattbrictson: I'm guessing that what sprockets 3.7.0 deprecated was removed in 4:
```
DEPRECATION WARNING: You are using the a deprecated processor interface #<Proc:0x007f9825d116f8@~/.rvm/gems/ruby-2.2.4@my_app/gems/xray-rails-0.1.21/lib/xray/engine.rb:22>.
Please update your processor interface:
https://github.com/rails/sprockets/blob/master/guides/extending_sprockets.md#supporting-all-versions-of-sprockets-in-processors
 (called from block in <class:Engine> at ~/.rvm/gems/ruby-2.2.4@my_app/gems/xray-rails-0.1.21/lib/xray/engine.rb:22)
DEPRECATION WARNING: You are using the a deprecated processor interface #<Proc:0x007f9827c0b2c0@~/.rvm/gems/ruby-2.2.4@my_app/gems/xray-rails-0.1.21/lib/xray/engine.rb:56>.
Please update your processor interface:
https://github.com/rails/sprockets/blob/master/guides/extending_sprockets.md#supporting-all-versions-of-sprockets-in-processors
 (called from block in <class:Engine> at ~/.rvm/gems/ruby-2.2.4@my_app/gems/xray-rails-0.1.21/lib/xray/engine.rb:56)
```

**Comment by patleb** [comment]
@mattbrictson, sorry, forgot about it. To answer your questions:

- the registration interface has changed, now you need to pass un object instead of a block

- the error message was about what I just said

- my commit changes the registration with something that works for Sprockets 2, 3 and 4 (although, `.jst` won't work, I made a mistake... should have been registered as a preprocessor)

- yes, it should

**Comment by mattbrictson** [comment]
OK, thanks for the additional info. I would like to turn this into an actual PR so that we can do a more thorough review.

@patleb Are you comfortable taking the lead on these changes and doing a PR? Is there anything you need help with?

**Comment by patleb** [comment]
Yep, I'll look into it, but can't tell you when it's gonna be completed, I'm busy with other stuff right now. No help needed, thanks!

**Comment by mattbrictson** [comment]
I stumbled across this commit in another project. It may shed some light on what is required for Sprockets 4 compatibility.

https://github.com/ai/autoprefixer-rails/commit/cd9b2ef1d5a89042e4d97614490ab03fa895a653

**Comment by patleb** [comment]
Thx. Sorry for the late feedback, but I'm on the clock to deliver a project, so I think it might take at least a couple of weeks before I look into it.

**Comment by evolve2k** [comment]
bump

**Comment by mattbrictson** [comment]
@evolve2k Have you tried xray-rails 0.2.0?

**Comment by evolve2k** [comment]
Cheers @mattbrictson. Woops hadn't noticed that 0.2.0 had landed. 
Yes updgrading to 0.2.0 fixed the deprecation warnings for me.

Is this issue resolved then?

**Comment by mattbrictson** [comment]
Sounds like it is resolved. Thanks for verifying!
