### ISSUE TITLE
"Screenshot" and "See Xray in action" links in the README are not working

### ISSUE THREAD

**Issue by nagi** [brentd/xray-rails#86]
![screen shot 2017-09-06 at 11 46 21](https://user-images.githubusercontent.com/1297635/30108151-1d265042-92f9-11e7-9e42-7fc5ebd96d7b.png)

**Comment by mattbrictson** [comment]
Thanks for the report! I am not the original author of this repo, so I don't have access to these files, which were hosted elsewhere. However, I was able to find the screenshot in the Internet Archive, so can at least restore that one.
