### ISSUE TITLE
Open in rubymine

### ISSUE THREAD

**Issue by alexey** [brentd/xray-rails#93]
Hi,

just followed with .xrayconfig:

```
:editor: 'mine $file'
```

but it just open the rubymine without file .. Anyone had similar issue ?

**Comment by dvanoni** [comment]
This is what my `.xrayconfig` file looks like, and it seems to be working for me:
```
---
:editor: mine
```

Note that there is an [issue](https://youtrack.jetbrains.com/issue/ALL-1266) with the command line launchers if you use the JetBrains Toolbox to install/update RubyMine (or any other JetBrains IDE). If you've used the Toolbox to update RubyMine, you might need to reinstall the command line launcher from the menu: __Tools > Create Command-line Launcher...__

To test if the command line launcher is working, try running it from a terminal to see if it works there, e.g.
```sh
mine app/views/layouts/application.html.erb
```

**Comment by alexey** [comment]
thanks @dvanoni, this did the trick !
**Tools > Create Command-line Launcher > Confirm**
